"""initial migration

Revision ID: b60dac8d8fc9
Revises: 
Create Date: 2026-03-16 09:06:58.953730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60dac8d8fc9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sponsor', sa.String(length=200), nullable=True),
    sa.Column('sponsor_party', sa.String(length=50), nullable=True),
    sa.Column('chamber', sa.String(length=20), nullable=True),
    sa.Column('congress_session', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('INTRODUCED', 'IN_COMMITTEE', 'PASSED_HOUSE', 'PASSED_SENATE', 'ENACTED', 'VETOED', 'FAILED', name='billstatus'), nullable=True),
    sa.Column('introduced_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_action_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_action', sa.String(length=500), nullable=True),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('sentiment_label', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', 'MIXED', name='sentimentlabel'), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('yea_votes', sa.Integer(), nullable=True),
    sa.Column('nay_votes', sa.Integer(), nullable=True),
    sa.Column('abstain_votes', sa.Integer(), nullable=True),
    sa.Column('vote_data', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_bill_number'), 'bills', ['bill_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bills_bill_number'), table_name='bills')
    op.drop_table('bills')
    # ### end Alembic commands ###
